[window]
opacity = 0.90

[mouse]
hide_when_typing = true

[keyboard]
bindings = [{key = "Enter", mods = "Super", action = "SpawnNewInstance"}]

[font]
normal = {family = "SauceCodePro Nerd Font", style = "Light"}
size = 14

# Default colors
[colors.primary]
background = '#000000'
foreground = '#f2f4f8'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#ee5396'
green   = '#25be6a'
yellow  = '#08bdba'
blue    = '#78a9ff'
magenta = '#be95ff'
cyan    = '#33b1ff'
white   = '#dfdfe0'

# Brightcolors
[colors.bright]
black   = '#484848'
red     = '#f16da6'
green   = '#46c880'
yellow  = '#2dc7c4'
blue    = '#8cb6ff'
magenta = '#c8a5ff'
cyan    = '#52bdff'
white   = '#e4e4e5'
